### ISSUE TITLE
Error in mkAssay(BRCA, log = TRUE, counts_to_CPM = TRUE) :    input_name must be an SE_obj assay

### ISSUE THREAD

**Issue by BirongZhang** [compbiomed/TBSignatureProfiler#28]
Hi all,

 Thanks for developing such a cool package!

When I run the sample data, it worked well! 
However, when I tried to use my own data, I ran into some problems. Because my metadata data and counts data are in a simple .csv format, I need to create a SummarizeExperiment () object by myself. Then I just followed  this tutorial [SummarizedExperiment](https://www.bioconductor.org/help/course-materials/2019/BSS2019/04_Practical_CoreApproachesInBioconductor.html#constructing-a-summarizedexperiment-object-by-hand), and did the following steps:

```
> coldata <- read.table("clin_metadata.csv",header = T,sep = ",", row.names=1)
> coldata[1:3,1:3]
             days_to_initial_pathologic_diagnosis last_contact_days_to death_days_to
TCGA.A8.A08L                                    0      [Not Available]            30
TCGA.UU.A93S                                    0      [Not Available]           116
TCGA.A2.A0CU                                    0      [Not Available]           158

> counts <- read.delim("counts_anno.csv", header = T, sep=",", row.names=1)
> counts[1:3,1:3]
       TCGA.A8.A08L TCGA.UU.A93S TCGA.A2.A0CU
TSPAN6         4150          351         1439
TNMD             17           36           73
DPM1           3870         1315         1683

> BRCA <- SummarizedExperiment(counts, colData = coldata)
> BRCA
class: SummarizedExperiment 
dim: 38660 55 
metadata(0):
**assays(1): ''**
rownames(38660): TSPAN6 TNMD ... HERC2P7 LINC01144
rowData names(0):
colnames(55): TCGA.A8.A08L TCGA.UU.A93S ... TCGA.B6.A0RI TCGA.B6.A0RU
colData names(6): days_to_initial_pathologic_diagnosis last_contact_days_to ...
  metastatic_tumor_indicator Treatment

**> assays(BRCA) 
List of length 1**

**> BRCA <- mkAssay(BRCA, log = TRUE, counts_to_CPM = TRUE)
Error in mkAssay(BRCA, log = TRUE, counts_to_CPM = TRUE) : 
  input_name must be an SE_obj assay**
```
I think I had some problems creating SummarizeExperiment(), **_because my assays(BRCA) only have "List of Length 1" and not "names(1): counts"_**. But I don't know what should I do.

Any advice would be highly appreciated! Thanks!

**Comment by aubreyodom** [comment]
Hi Birong,
Thanks for using our package!

I think you are correct in your assessment that the issue is due to the assay attribute of your BRCA object. In order to make a sumarizedExperiment object with a named "counts" assay, I think this should do the trick:

`BRCA <- SummarizedExperiment(assays = list("counts" = as.matrix(counts)),  colData = coldata)`

The difference is that you are creating a named assay with a list format.

Let me know how that works for you!
Brie

**Comment by BirongZhang** [comment]
Hi Brie,

Thanks for your efficient reply! It works well now!

Another question, if I want to focus on the immune cells of these patients, can I use other immune cell signature references. For example [xCell gene set] (https://github.com/cansysbio/ConsensusTME/blob/master/data-raw/xCell_genes.txt),  it is ok?

Thanks again for your kind help!

**Comment by aubreyodom** [comment]
Hi Birong,
Glad that worked!

For your second question, based on the linked set it sounds like you're hoping to using your own list of gene signatures to evaluate on immune cells - this is totally doable! All you need to do is make a signatures object that has the same named list format as the TBsignatures object included in the package, and then supply that in any functions that you use by setting the signatures argument to your own immune cell signature object. If you come across any problems with doing so, I'm happy to help out.

**Comment by BirongZhang** [comment]
Hi Brie,

Thanks so much for your kind help!
I have tried, and  it works great! I do love your package!

Another small question, the "singscore" algorithm doesn't seem to work for me, could you please take a look?
```
compareAlgs(BRCA, 
+             annotationColName = "Treatment",
+             scale = TRUE,
+             algorithm = c("GSVA", "ssGSEA", "singscore", "PLAGE", "Zscore"),
+             useAssay = "log_counts",
+             signatures = Signature ["Macrophages.M2"],
+             choose_color = col.me, 
+             show.pb = FALSE,
+             parallel.sz = 1, output = "boxplot")
Running GSVA
Running ssGSEA
Running PLAGE
Running Z-score profiling
Running singscore
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simpleScore’ for signature ‘"matrix", "NULL", "missing"’
In addition: Warning messages:
1: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
2: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
3: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
4: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
5: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
6: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
7: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
```

And here is my Signature file:
<img width="763" alt="Screenshot 2022-01-19 at 10 51 05" src="https://user-images.githubusercontent.com/74430395/150115907-e28d6d2b-80dd-4450-9191-500c1335502c.png">

Let me know if you need more details. Many thanks!

**Comment by aubreyodom** [comment]
Hi Birong,

Good catch. I just tried a few test cases with other data, and it seems to be popping up whenever more than one signature is included in the signatures object. I will need to dig into the code for the runTBsigProfiler() to fix this. It looks like the other scoring algorithms should work fine in the meantime. I'll keep you updated on when I get that fixed.

Thanks,
Brie

**Comment by aubreyodom** [comment]
Hi Birong,
I fixed the bug - looks like singscore was not working for user-provided signatures, so I've updated the function.
Best,
Brie

**Comment by BirongZhang** [comment]
Hi Brie,

Thanks so much for your work and time!

I just reinstalled the package and tried it out using the previous data. Maybe I got something wrong and it still seems to have some problems:
```
> out <- capture.output(ssgsea_result <- runTBsigProfiler(input = BRCA,
+                                                         useAssay = "log_cpm",
+                                                         signatures = Signature ,
+                                                         algorithm = "singscore",
+                                                         combineSigAndAlgorithm = TRUE,
+                                                         parallel.sz = 1))
Running singscore
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simpleScore’ for signature ‘"matrix", "NULL", "missing"’

> compareAlgs(BRCA, 
+             annotationColName = "Treatment",
+             scale = TRUE,
+             algorithm = c("singscore"),
+             useAssay = "log_counts",
+             signatures = Signature ["Macrophages.M2"],
+             choose_color = col.me, 
+             show.pb = FALSE,
+             parallel.sz = 1)
Running singscore
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simpleScore’ for signature ‘"matrix", "NULL", "missing"’

> compareAlgs(BRCA, 
+             annotationColName = "Treatment",
+             scale = TRUE,
+             algorithm = c("singscore"),
+             useAssay = "log_counts",
+             signatures = Signature ["Macrophages.M2"],
+             choose_color = col.me, 
+             show.pb = FALSE,
+             parallel.sz = 1, output = "boxplot")
Running singscore
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simpleScore’ for signature ‘"matrix", "NULL", "missing"’

> compareAlgs(BRCA, 
+             annotationColName = "Treatment",
+             scale = TRUE,
+             algorithm = c("GSVA", "ssGSEA",  "PLAGE", "Zscore","singscore"),
+             useAssay = "log_counts",
+             signatures = Signature ["Macrophages.M2"],
+             choose_color = col.me, 
+             show.pb = FALSE,
+             parallel.sz = 1)
Running GSVA
Running ssGSEA
Running PLAGE
Running Z-score profiling
Running singscore
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simpleScore’ for signature ‘"matrix", "NULL", "missing"’
In addition: Warning messages:
1: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
2: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
3: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
4: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
5: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
6: In .filterFeatures(expr, method) :
  3568 genes with constant expression values throuhgout the samples.
7: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
```

# my signature
```
library(ConsensusTME)
Signature <- ConsensusTME::methodSignatures$xCell 
```

Let me know if you need more details. Many thanks!

Kind regards,
Birong

**Comment by aubreyodom** [comment]
Hi Birong,
Did you install the development version? The BiocManager won't have the most updated package.

You'll need to run this code:
`devtools::install("compbiomed/tbsignatureprofiler")`

If that doesn't do the trick, I'll take another look.

Best,
Brie

**Comment by BirongZhang** [comment]
Hi Brie,

Thanks for your efficient reply!

You're right, I just used BiocManager().
I'm now using devtools(). However, my R version is 4.0.3...
```
ERROR: this R is version 4.0.3, package 'TBSignatureProfiler' requires  R >= 4.1
Warning messages:
1: In i.p(...) :
  installation of package ‘RcppArmadillo’ had non-zero exit status
2: In i.p(...) : installation of package ‘Cairo’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/c5/6c_hbb551sq7qx62n_hqz5s40000gs/T//RtmpYOvCAc/file66c24a9301c/TBSignatureProfiler_1.6.12.tar.gz’ had non-zero exit status
```

I need time to update my R. You can close this issue and I will come back if I have other questions.

Thanks for your help all the time!

Best regards,
Birong

**Comment by aubreyodom** [comment]
Got it. Happy to help!
